version: '3.9'

services:
  postgres:
    image: postgres:15
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - "25432:5432"
    volumes:
      - reco_pgdata:/var/lib/postgresql/data
    networks:
      - lmsnet

  reco:
    build:
      context: .
    environment:
      DATABASE_URL: postgres://postgres:password@postgres:5432/reco_development
    depends_on:
      - postgres
    ports:
      - "3002:3000"
    volumes:
      - .:/app
    command: bash -c "if [ ! -f spec/rails_helper.rb ]; then bundle exec rails generate rspec:install; fi && bundle exec rails db:create db:migrate && bundle exec rails server -b 0.0.0.0"
    networks:
      - lmsnet

volumes:
  reco_pgdata:

networks:
  lmsnet:
    external: true 